# Generated by Django 5.1.2 on 2024-10-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofolio', '0002_culturalevent_culturalworkshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalevent',
            name='event_type',
            field=models.CharField(choices=[('concert', 'Concert'), ('exhibition', 'Exhibition'), ('festival', 'Festival'), ('theater', 'Theater')], default='concert', max_length=50, verbose_name='Event Type'),
            preserve_default=False,
        ),
    ]
