# Generated by Django 5.1.2 on 2024-10-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photofolio', '0003_culturalevent_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalworkshop',
            name='end_time',
        ),
    ]
