# Generated by Django 5.1.2 on 2024-10-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofolio', '0004_remove_culturalworkshop_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalworkshop',
            name='program',
            field=models.TextField(blank=True, null=True),
        ),
    ]
